apiVersion: v1
kind: Pod
metadata:
  name: shell-operator
  namespace: default
spec:
  containers:
    - name: shell-operator
      image: piotrzan/shell-operator:pods-hooks.v1
      imagePullPolicy: Always
  serviceAccountName: monitor-pods-acc
